[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
dependencies = []
name = "stability-nexus"
version = "1.0.0"
description = "Stability Nexus multi-protocol simulation library."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Luca D'Angelo", email = "ldgaetano@protonmail.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://stability.nexus"

[tool.hatch.build.targets.wheel]
packages = ["src/stability_nexus"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
stability_nexus = { path = ".", editable = true }

[tool.pixi.tasks]
