name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: latest

      - run: pixi install

      - run: pixi run pytest

      - run: pixi run build
